# Generated by Django 5.2.8 on 2025-11-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và Tên')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('id_type', models.CharField(choices=[('CCCD', 'Căn cước Công dân'), ('CMND', 'Chứng minh Nhân dân'), ('PP', 'Hộ chiếu (Passport)'), ('OTHER', 'Khác')], default='CCCD', max_length=10, verbose_name='Loại giấy tờ')),
                ('id_number', models.CharField(max_length=50, unique=True, verbose_name='Mã số giấy tờ')),
                ('address', models.CharField(max_length=500, verbose_name='Địa chỉ thường trú')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '3. Khách hàng',
                'verbose_name_plural': '3. Quản lý Khách hàng',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Khách sạn')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Khách sạn')),
            ],
            options={
                'verbose_name': '1. Khách sạn',
                'verbose_name_plural': '1. Quản lý Khách sạn',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Số Phòng')),
                ('room_type', models.CharField(max_length=50, verbose_name='Loại Phòng')),
                ('price_per_night', models.DecimalField(decimal_places=0, default=500000, max_digits=10, verbose_name='Giá/Đêm')),
                ('status', models.CharField(choices=[('Vacant', 'Trống (Xanh)'), ('Dirty', 'Cần dọn (Xám)'), ('Occupied', 'Đang có khách (Đỏ)'), ('Booked', 'Đã đặt (Vàng)')], default='Vacant', max_length=20, verbose_name='Trạng thái')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.hotel', verbose_name='Khách sạn')),
            ],
            options={
                'verbose_name': '2. Phòng',
                'verbose_name_plural': '2. Quản lý Phòng',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(verbose_name='Thời gian Check-in')),
                ('check_out_date', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian Check-out dự kiến')),
                ('status', models.CharField(choices=[('Confirmed', 'Đã xác nhận (Booking)'), ('Occupied', 'Đang cư trú'), ('Completed', 'Đã hoàn tất'), ('Cancelled', 'Đã hủy')], default='Confirmed', max_length=20, verbose_name='Trạng thái đặt phòng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.guest', verbose_name='Khách hàng')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.room', verbose_name='Phòng')),
            ],
            options={
                'verbose_name': '4. Đặt phòng',
                'verbose_name_plural': '4. Quản lý Đặt phòng',
                'ordering': ['check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='GuestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung yêu cầu')),
                ('status', models.CharField(choices=[('New', 'Mới'), ('Processing', 'Đang xử lý'), ('Completed', 'Hoàn thành')], default='New', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Giao cho nhân viên')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.reservation', verbose_name='Booking liên quan')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.room', verbose_name='Phòng yêu cầu')),
            ],
            options={
                'verbose_name': '6. Yêu cầu Khách',
                'verbose_name_plural': '6. Quản lý Yêu cầu Khách',
            },
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Tên Dịch vụ/Sản phẩm')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.reservation', verbose_name='Đặt phòng')),
            ],
            options={
                'verbose_name': '5. Dịch vụ',
                'verbose_name_plural': '5. Quản lý Dịch vụ & Phụ phí',
            },
        ),
    ]
