# Generated by Django 5.2.8 on 2025-11-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True, verbose_name='Tên Dịch vụ/Sản phẩm')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá hiện tại')),
            ],
            options={
                'verbose_name': '7. Danh mục Dịch vụ',
                'verbose_name_plural': '7. Quản lý Danh mục Dịch vụ',
            },
        ),
    ]
