# Generated by Django 5.2.8 on 2025-11-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Biển số xe'),
        ),
    ]
