# Generated by Django 5.2.8 on 2025-11-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_guest_license_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, verbose_name='Tên Nhân viên')),
                ('role', models.CharField(choices=[('Reception', 'Lễ tân'), ('Housekeeping', 'Buồng phòng'), ('Guard', 'Bảo vệ')], max_length=20, verbose_name='Vị trí')),
                ('date', models.DateField(verbose_name='Ngày làm việc')),
                ('shift', models.CharField(choices=[('Morning', 'Ca Sáng (6h-14h)'), ('Afternoon', 'Ca Chiều (14h-22h)'), ('Night', 'Ca Đêm (22h-6h)')], max_length=20, verbose_name='Ca làm việc')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': '8. Lịch làm việc',
                'verbose_name_plural': '8. Quản lý Lịch làm việc',
                'ordering': ['-date', 'shift'],
            },
        ),
    ]
