# Generated by Django 5.2.8 on 2025-11-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_staffschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='guest_ids/', verbose_name='Ảnh giấy tờ'),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Ca Sáng'), ('Afternoon', 'Ca Chiều'), ('Night', 'Ca Đêm')], max_length=20, verbose_name='Ca làm việc'),
        ),
    ]
