# Generated by Django 5.2.8 on 2025-11-21 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0005_guest_photo_alter_staffschedule_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="guest_ids/",
                verbose_name="Ảnh đại diện (Cũ)",
            ),
        ),
        migrations.AlterField(
            model_name="staffschedule",
            name="shift",
            field=models.CharField(
                choices=[
                    ("Morning", "Ca Sáng (7h-15h)"),
                    ("Afternoon", "Ca Chiều (15h-23h)"),
                    ("Night", "Ca Đêm (23h-7h)"),
                ],
                max_length=20,
                verbose_name="Ca làm việc",
            ),
        ),
        migrations.CreateModel(
            name="GuestPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="guest_ids/", verbose_name="Ảnh giấy tờ"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="pms.guest",
                        verbose_name="Khách hàng",
                    ),
                ),
            ],
        ),
    ]
