# Generated by Django 5.2.8 on 2025-11-22 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_alter_guest_photo_alter_staffschedule_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='photo',
        ),
        migrations.AddField(
            model_name='guest',
            name='photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='guest_ids/', verbose_name='Ảnh mặt sau'),
        ),
        migrations.AddField(
            model_name='guest',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='guest_ids/', verbose_name='Ảnh mặt trước'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='occupants',
            field=models.ManyToManyField(blank=True, related_name='stays', to='pms.guest', verbose_name='Danh sách khách ở'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id_type',
            field=models.CharField(choices=[('CCCD', 'Căn cước Công dân'), ('CMND', 'Chứng minh Nhân dân'), ('PP', 'Hộ chiếu'), ('OTHER', 'Khác')], default='CCCD', max_length=10, verbose_name='Loại giấy tờ'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_bookings', to='pms.guest', verbose_name='Người đặt chính'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Đã xác nhận'), ('Occupied', 'Đang cư trú'), ('Completed', 'Đã hoàn tất'), ('Cancelled', 'Đã hủy')], default='Confirmed', max_length=20, verbose_name='Trạng thái đặt phòng'),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='Tên Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='item_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Ca Sáng (7h-15h)'), ('Afternoon', 'Ca Chiều (15h-22h)'), ('Night', 'Ca Đêm (22h-7h)')], max_length=20, verbose_name='Ca làm việc'),
        ),
        migrations.DeleteModel(
            name='GuestPhoto',
        ),
    ]
