# Generated by Django 5.2.8 on 2025-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_remove_guest_photo_guest_photo_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Tiền đặt cọc'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Vacant', 'Phòng Trống'), ('Dirty', 'Chờ Dọn Dẹp'), ('Occupied', 'Đang Có Khách'), ('Booked', 'Khách Đặt Trước')], default='Vacant', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
